"""add role_id and role attributes in users

Revision ID: fdae8f75db9d
Revises: 4bfdc64981e9
Create Date: 2025-09-25 21:32:39.151783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdae8f75db9d'
down_revision = '4bfdc64981e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_role_user', 'roles', ['role_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_role_user', type_='foreignkey')
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###
